site_name: CUBRID Vector Database
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - bnf
    - sql
plugins:
  - search
  - print-site

markdown_extensions:
  - mdx_truly_sane_lists:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Vector DDL: vector-ddl.md
  - Vector DML: vector-dml.md
  - Vector Index: vector-index.md
  - Vector Operations: vector-operations.md
