site_name: CUBRID Vector Database
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Vector DDL: vector-ddl.md
  - Vector DML: vector-dml.md
  - Vector Index: vector-index.md
